# Generated by Django 3.0.3 on 2021-10-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(db_column='Id',
                                        primary_key=True, serialize=False)),
                ('data', models.CharField(db_column='Data', max_length=255)),
                ('ipaddress', models.CharField(db_column='IPAddress', max_length=50)),
                ('license', models.CharField(blank=True,
                                             db_column='License', max_length=255, null=True)),
            ],
            options={
                'db_table': 'License',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('net_id', models.CharField(max_length=200)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Surname', models.CharField(blank=True, max_length=200)),
                ('Active', models.BooleanField(default=False)),
                ('FullAccess', models.BooleanField(default=False)),
                ('LicenseSignAccess', models.BooleanField(default=False)),
            ],
        ),
    ]
